name: Codecov CI

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - uses: conda-incubator/setup-miniconda@v2
          with:
              auto-update-conda: true
              python-version: '3.8.13'

        - name: Generate coverage report
          run: |
              pip install pytest==7.1.2
              pip install pytest-cov==3.0.0
              pip install pytest-asyncio==0.19.0
              python -m pytest --cov=./app ./app/tests --cov-report=xml
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v3
          with:
              directory: ./coverage/reports/
              env_vars: OS,PYTHON
              fail_ci_if_error: true
              files: ./coverage1.xml,./coverage2.xml
              flags: unittests
              name: codecov-umbrella
              path_to_write_report: ./coverage/codecov_report.txt
              verbose: true
