name: Deploy to dev env

on: [push]
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - uses: conda-incubator/setup-miniconda@v2
              with:
                  auto-update-conda: true
                  python-version: '3.8.13'

            - name: install bentoml
              shell: bash
              run: |
                  pip3 install -r requirements.txt

            - name: save pytorch model
              run: |
                  python3 ./app/model.py

#            - name: build docker file and setting deploy files
#              env:
#                  IMAGE_TAG: ${{ github.sha }}
#              run: |
#                  bentoml build
#                  bentoml containerize keyword_service:latest -t keyword_service:$IMAGE_TAG

            - name: aws configure
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ap-northeast-2

            - name: Login to ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: build docker file and setting deploy files
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: cs-broker/ai
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  bentoml containerize keyword_service:latest -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
